// Per-page Open Graph images: short, punchy titles rendered onto a branded
// card at build time (see src/pages/og/[slug].png.ts). Keyed by the page's
// last path segment ('index' = the landing page). Locale variants of a page
// reuse the same image.
export interface OgPage {
  title: string;
  eyebrow: string;
}

export const OG_PAGES: Record<string, OgPage> = {
  index: { eyebrow: 'AI FUNSCRIPT GENERATOR', title: 'Turn any video into a funscript' },
  'generate-funscripts-from-video': {
    eyebrow: 'HOW IT WORKS',
    title: 'Generate a funscript from any video',
  },
  'vr-funscripts': { eyebrow: 'VR', title: 'VR funscripts, generated by AI' },
  'what-is-a-funscript': { eyebrow: 'EXPLAINER', title: 'What is a funscript?' },
  'funscript-editor': { eyebrow: 'EDITOR', title: 'A frame-accurate funscript editor' },
  'funscripts-for-jav-and-javr': { eyebrow: 'JAV / JAVR', title: 'Funscripts for JAV & JAVR' },
  'funscripts-for-osr2-sr6': {
    eyebrow: 'MULTI-AXIS',
    title: 'Multi-axis funscripts for OSR2 / SR6',
  },
  'funscripts-for-the-handy': { eyebrow: 'THE HANDY', title: 'Funscripts for The Handy' },
  'supported-devices': { eyebrow: 'DEVICES', title: 'Every device FunGen drives' },
  'stash-xbvr-funscripts': {
    eyebrow: 'STASH / XBVR',
    title: 'Funscripts from your Stash & XBVR library',
  },
  changelog: { eyebrow: 'RELEASES', title: "What's new in FunGen" },
  pricing: { eyebrow: 'PRICING', title: 'Try it free. Unlock the full potential.' },
  ai: { eyebrow: 'AI MODELS', title: 'Two AI models, made for funscripts' },
};

/// The OG slug for a canonical path (last segment; landing -> 'index').
export function ogSlug(canonicalPath: string | undefined): string {
  if (!canonicalPath) return 'index';
  const seg = canonicalPath.replace(/\/+$/, '').split('/').pop() || '';
  return seg && OG_PAGES[seg] ? seg : 'index';
}
